version: '3.7'
networks:
  backend:
volumes:
  home:
services:
  ood:
    build:
      context: .
      target: ood
    container_name: docker-with-slurm-ood
    hostname: ood
    ports:
      - 5556:5556
      - 8080:8080
    networks:
      - backend
    depends_on:
      - head
    volumes:
      - home:/home
      - ../common/example.yml:/etc/ood/config/clusters.d/example.yml
  head:
    build:
      context: .
      target: head
    container_name: docker-with-slurm-head
    hostname: head
    networks:
      - backend
    volumes:
      - home:/home
